package com.example.familyapplication.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.familyapplication.db.Contacts;
import com.example.familyapplication.db.Users;

import com.example.familyapplication.db.greendao.ContactsDao;
import com.example.familyapplication.db.greendao.UsersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsDaoConfig;
    private final DaoConfig usersDaoConfig;

    private final ContactsDao contactsDao;
    private final UsersDao usersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsDaoConfig = daoConfigMap.get(ContactsDao.class).clone();
        contactsDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        contactsDao = new ContactsDao(contactsDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);

        registerDao(Contacts.class, contactsDao);
        registerDao(Users.class, usersDao);
    }
    
    public void clear() {
        contactsDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
    }

    public ContactsDao getContactsDao() {
        return contactsDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

}
